// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: loan.proto

package loan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoanStatus int32

const (
	LoanStatus_LOAN_STATUS_UNSPECIFIED LoanStatus = 0
	LoanStatus_BORROWED                LoanStatus = 1
	LoanStatus_RETURN_PENDING          LoanStatus = 2
	LoanStatus_RETURNED                LoanStatus = 3
)

// Enum value maps for LoanStatus.
var (
	LoanStatus_name = map[int32]string{
		0: "LOAN_STATUS_UNSPECIFIED",
		1: "BORROWED",
		2: "RETURN_PENDING",
		3: "RETURNED",
	}
	LoanStatus_value = map[string]int32{
		"LOAN_STATUS_UNSPECIFIED": 0,
		"BORROWED":                1,
		"RETURN_PENDING":          2,
		"RETURNED":                3,
	}
)

func (x LoanStatus) Enum() *LoanStatus {
	p := new(LoanStatus)
	*p = x
	return p
}

func (x LoanStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoanStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_loan_proto_enumTypes[0].Descriptor()
}

func (LoanStatus) Type() protoreflect.EnumType {
	return &file_loan_proto_enumTypes[0]
}

func (x LoanStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoanStatus.Descriptor instead.
func (LoanStatus) EnumDescriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{0}
}

type Loan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookName      string                 `protobuf:"bytes,4,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	Status        LoanStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=loan.LoanStatus" json:"status,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	ReturnedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=returned_at,json=returnedAt,proto3" json:"returned_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	DeliveryCode  string                 `protobuf:"bytes,11,opt,name=delivery_code,json=deliveryCode,proto3" json:"delivery_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{0}
}

func (x *Loan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Loan) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Loan) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Loan) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *Loan) GetStatus() LoanStatus {
	if x != nil {
		return x.Status
	}
	return LoanStatus_LOAN_STATUS_UNSPECIFIED
}

func (x *Loan) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Loan) GetReturnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReturnedAt
	}
	return nil
}

func (x *Loan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Loan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Loan) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Loan) GetDeliveryCode() string {
	if x != nil {
		return x.DeliveryCode
	}
	return ""
}

type CreateLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookName      string                 `protobuf:"bytes,4,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanRequest) Reset() {
	*x = CreateLoanRequest{}
	mi := &file_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequest) ProtoMessage() {}

func (x *CreateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLoanRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateLoanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLoanRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *CreateLoanRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type CreateLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanResponse) Reset() {
	*x = CreateLoanResponse{}
	mi := &file_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanResponse) ProtoMessage() {}

func (x *CreateLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLoanResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

type ClaimLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimLoanRequest) Reset() {
	*x = ClaimLoanRequest{}
	mi := &file_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimLoanRequest) ProtoMessage() {}

func (x *ClaimLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimLoanRequest.ProtoReflect.Descriptor instead.
func (*ClaimLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{3}
}

func (x *ClaimLoanRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *ClaimLoanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BookName      string                 `protobuf:"bytes,2,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	Status        LoanStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=loan.LoanStatus" json:"status,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,5,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoanRequest) Reset() {
	*x = UpdateLoanRequest{}
	mi := &file_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoanRequest) ProtoMessage() {}

func (x *UpdateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoanRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLoanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLoanRequest) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *UpdateLoanRequest) GetStatus() LoanStatus {
	if x != nil {
		return x.Status
	}
	return LoanStatus_LOAN_STATUS_UNSPECIFIED
}

func (x *UpdateLoanRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *UpdateLoanRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

type GetLoanByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanByIDRequest) Reset() {
	*x = GetLoanByIDRequest{}
	mi := &file_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanByIDRequest) ProtoMessage() {}

func (x *GetLoanByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLoanByIDRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{5}
}

func (x *GetLoanByIDRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type GetLoanByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanByIDResponse) Reset() {
	*x = GetLoanByIDResponse{}
	mi := &file_loan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanByIDResponse) ProtoMessage() {}

func (x *GetLoanByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLoanByIDResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{6}
}

func (x *GetLoanByIDResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

type ListLoansByOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansByOwnerRequest) Reset() {
	*x = ListLoansByOwnerRequest{}
	mi := &file_loan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansByOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansByOwnerRequest) ProtoMessage() {}

func (x *ListLoansByOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansByOwnerRequest.ProtoReflect.Descriptor instead.
func (*ListLoansByOwnerRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{7}
}

func (x *ListLoansByOwnerRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListLoansByOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoansByOwnerResponse) Reset() {
	*x = ListLoansByOwnerResponse{}
	mi := &file_loan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoansByOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoansByOwnerResponse) ProtoMessage() {}

func (x *ListLoansByOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoansByOwnerResponse.ProtoReflect.Descriptor instead.
func (*ListLoansByOwnerResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{8}
}

func (x *ListLoansByOwnerResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

type BanUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanUserRequest) Reset() {
	*x = BanUserRequest{}
	mi := &file_loan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanUserRequest) ProtoMessage() {}

func (x *BanUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanUserRequest.ProtoReflect.Descriptor instead.
func (*BanUserRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{9}
}

func (x *BanUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BanUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanUserRequest) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type DeliveryLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanID        string                 `protobuf:"bytes,1,opt,name=loanID,proto3" json:"loanID,omitempty"`
	UpdaterId     string                 `protobuf:"bytes,2,opt,name=updater_id,json=updaterId,proto3" json:"updater_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryLoanRequest) Reset() {
	*x = DeliveryLoanRequest{}
	mi := &file_loan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLoanRequest) ProtoMessage() {}

func (x *DeliveryLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLoanRequest.ProtoReflect.Descriptor instead.
func (*DeliveryLoanRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{10}
}

func (x *DeliveryLoanRequest) GetLoanID() string {
	if x != nil {
		return x.LoanID
	}
	return ""
}

func (x *DeliveryLoanRequest) GetUpdaterId() string {
	if x != nil {
		return x.UpdaterId
	}
	return ""
}

type DeliveryLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryCode  string                 `protobuf:"bytes,1,opt,name=delivery_code,json=deliveryCode,proto3" json:"delivery_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryLoanResponse) Reset() {
	*x = DeliveryLoanResponse{}
	mi := &file_loan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryLoanResponse) ProtoMessage() {}

func (x *DeliveryLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryLoanResponse.ProtoReflect.Descriptor instead.
func (*DeliveryLoanResponse) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{11}
}

func (x *DeliveryLoanResponse) GetDeliveryCode() string {
	if x != nil {
		return x.DeliveryCode
	}
	return ""
}

type ConfirmDeliveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanID        string                 `protobuf:"bytes,1,opt,name=loanID,proto3" json:"loanID,omitempty"`
	DeliveryCode  string                 `protobuf:"bytes,2,opt,name=delivery_code,json=deliveryCode,proto3" json:"delivery_code,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeliveryRequest) Reset() {
	*x = ConfirmDeliveryRequest{}
	mi := &file_loan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeliveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeliveryRequest) ProtoMessage() {}

func (x *ConfirmDeliveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmDeliveryRequest.ProtoReflect.Descriptor instead.
func (*ConfirmDeliveryRequest) Descriptor() ([]byte, []int) {
	return file_loan_proto_rawDescGZIP(), []int{12}
}

func (x *ConfirmDeliveryRequest) GetLoanID() string {
	if x != nil {
		return x.LoanID
	}
	return ""
}

func (x *ConfirmDeliveryRequest) GetDeliveryCode() string {
	if x != nil {
		return x.DeliveryCode
	}
	return ""
}

func (x *ConfirmDeliveryRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

var File_loan_proto protoreflect.FileDescriptor

const file_loan_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"loan.proto\x12\x04loan\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xdc\x03\n" +
	"\x04Loan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbook_name\x18\x04 \x01(\tR\bbookName\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.loan.LoanStatusR\x06status\x126\n" +
	"\bdeadline\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12;\n" +
	"\vreturned_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"returnedAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12#\n" +
	"\rdelivery_code\x18\v \x01(\tR\fdeliveryCode\"\xac\x01\n" +
	"\x11CreateLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbook_name\x18\x04 \x01(\tR\bbookName\x126\n" +
	"\bdeadline\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"4\n" +
	"\x12CreateLoanResponse\x12\x1e\n" +
	"\x04loan\x18\x01 \x01(\v2\n" +
	".loan.LoanR\x04loan\"D\n" +
	"\x10ClaimLoanRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc1\x01\n" +
	"\x11UpdateLoanRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tbook_name\x18\x02 \x01(\tR\bbookName\x12(\n" +
	"\x06status\x18\x03 \x01(\x0e2\x10.loan.LoanStatusR\x06status\x126\n" +
	"\bdeadline\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x05 \x01(\tR\tupdaterId\"-\n" +
	"\x12GetLoanByIDRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"5\n" +
	"\x13GetLoanByIDResponse\x12\x1e\n" +
	"\x04loan\x18\x01 \x01(\v2\n" +
	".loan.LoanR\x04loan\"4\n" +
	"\x17ListLoansByOwnerRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"<\n" +
	"\x18ListLoansByOwnerResponse\x12 \n" +
	"\x05loans\x18\x01 \x03(\v2\n" +
	".loan.LoanR\x05loans\"|\n" +
	"\x0eBanUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"L\n" +
	"\x13DeliveryLoanRequest\x12\x16\n" +
	"\x06loanID\x18\x01 \x01(\tR\x06loanID\x12\x1d\n" +
	"\n" +
	"updater_id\x18\x02 \x01(\tR\tupdaterId\";\n" +
	"\x14DeliveryLoanResponse\x12#\n" +
	"\rdelivery_code\x18\x01 \x01(\tR\fdeliveryCode\"p\n" +
	"\x16ConfirmDeliveryRequest\x12\x16\n" +
	"\x06loanID\x18\x01 \x01(\tR\x06loanID\x12#\n" +
	"\rdelivery_code\x18\x02 \x01(\tR\fdeliveryCode\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId*Y\n" +
	"\n" +
	"LoanStatus\x12\x1b\n" +
	"\x17LOAN_STATUS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bBORROWED\x10\x01\x12\x12\n" +
	"\x0eRETURN_PENDING\x10\x02\x12\f\n" +
	"\bRETURNED\x10\x032\xaa\x04\n" +
	"\vLoanService\x12?\n" +
	"\n" +
	"CreateLoan\x12\x17.loan.CreateLoanRequest\x1a\x18.loan.CreateLoanResponse\x12;\n" +
	"\tClaimLoan\x12\x16.loan.ClaimLoanRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\n" +
	"UpdateLoan\x12\x17.loan.UpdateLoanRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\vGetLoanByID\x12\x18.loan.GetLoanByIDRequest\x1a\x19.loan.GetLoanByIDResponse\x12Q\n" +
	"\x10ListLoansByOwner\x12\x1d.loan.ListLoansByOwnerRequest\x1a\x1e.loan.ListLoansByOwnerResponse\x127\n" +
	"\aBanUser\x12\x14.loan.BanUserRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fDeliveryLoan\x12\x19.loan.DeliveryLoanRequest\x1a\x1a.loan.DeliveryLoanResponse\x12G\n" +
	"\x0fConfirmDelivery\x12\x1c.loan.ConfirmDeliveryRequest\x1a\x16.google.protobuf.EmptyB\x19Z\x17/shared/proto/loan;loanb\x06proto3"

var (
	file_loan_proto_rawDescOnce sync.Once
	file_loan_proto_rawDescData []byte
)

func file_loan_proto_rawDescGZIP() []byte {
	file_loan_proto_rawDescOnce.Do(func() {
		file_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)))
	})
	return file_loan_proto_rawDescData
}

var file_loan_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_loan_proto_goTypes = []any{
	(LoanStatus)(0),                  // 0: loan.LoanStatus
	(*Loan)(nil),                     // 1: loan.Loan
	(*CreateLoanRequest)(nil),        // 2: loan.CreateLoanRequest
	(*CreateLoanResponse)(nil),       // 3: loan.CreateLoanResponse
	(*ClaimLoanRequest)(nil),         // 4: loan.ClaimLoanRequest
	(*UpdateLoanRequest)(nil),        // 5: loan.UpdateLoanRequest
	(*GetLoanByIDRequest)(nil),       // 6: loan.GetLoanByIDRequest
	(*GetLoanByIDResponse)(nil),      // 7: loan.GetLoanByIDResponse
	(*ListLoansByOwnerRequest)(nil),  // 8: loan.ListLoansByOwnerRequest
	(*ListLoansByOwnerResponse)(nil), // 9: loan.ListLoansByOwnerResponse
	(*BanUserRequest)(nil),           // 10: loan.BanUserRequest
	(*DeliveryLoanRequest)(nil),      // 11: loan.DeliveryLoanRequest
	(*DeliveryLoanResponse)(nil),     // 12: loan.DeliveryLoanResponse
	(*ConfirmDeliveryRequest)(nil),   // 13: loan.ConfirmDeliveryRequest
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
}
var file_loan_proto_depIdxs = []int32{
	0,  // 0: loan.Loan.status:type_name -> loan.LoanStatus
	14, // 1: loan.Loan.deadline:type_name -> google.protobuf.Timestamp
	14, // 2: loan.Loan.returned_at:type_name -> google.protobuf.Timestamp
	14, // 3: loan.Loan.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: loan.Loan.updated_at:type_name -> google.protobuf.Timestamp
	14, // 5: loan.Loan.deleted_at:type_name -> google.protobuf.Timestamp
	14, // 6: loan.CreateLoanRequest.deadline:type_name -> google.protobuf.Timestamp
	1,  // 7: loan.CreateLoanResponse.loan:type_name -> loan.Loan
	0,  // 8: loan.UpdateLoanRequest.status:type_name -> loan.LoanStatus
	14, // 9: loan.UpdateLoanRequest.deadline:type_name -> google.protobuf.Timestamp
	1,  // 10: loan.GetLoanByIDResponse.loan:type_name -> loan.Loan
	1,  // 11: loan.ListLoansByOwnerResponse.loans:type_name -> loan.Loan
	14, // 12: loan.BanUserRequest.expired_at:type_name -> google.protobuf.Timestamp
	2,  // 13: loan.LoanService.CreateLoan:input_type -> loan.CreateLoanRequest
	4,  // 14: loan.LoanService.ClaimLoan:input_type -> loan.ClaimLoanRequest
	5,  // 15: loan.LoanService.UpdateLoan:input_type -> loan.UpdateLoanRequest
	6,  // 16: loan.LoanService.GetLoanByID:input_type -> loan.GetLoanByIDRequest
	8,  // 17: loan.LoanService.ListLoansByOwner:input_type -> loan.ListLoansByOwnerRequest
	10, // 18: loan.LoanService.BanUser:input_type -> loan.BanUserRequest
	11, // 19: loan.LoanService.DeliveryLoan:input_type -> loan.DeliveryLoanRequest
	13, // 20: loan.LoanService.ConfirmDelivery:input_type -> loan.ConfirmDeliveryRequest
	3,  // 21: loan.LoanService.CreateLoan:output_type -> loan.CreateLoanResponse
	15, // 22: loan.LoanService.ClaimLoan:output_type -> google.protobuf.Empty
	15, // 23: loan.LoanService.UpdateLoan:output_type -> google.protobuf.Empty
	7,  // 24: loan.LoanService.GetLoanByID:output_type -> loan.GetLoanByIDResponse
	9,  // 25: loan.LoanService.ListLoansByOwner:output_type -> loan.ListLoansByOwnerResponse
	15, // 26: loan.LoanService.BanUser:output_type -> google.protobuf.Empty
	12, // 27: loan.LoanService.DeliveryLoan:output_type -> loan.DeliveryLoanResponse
	15, // 28: loan.LoanService.ConfirmDelivery:output_type -> google.protobuf.Empty
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_loan_proto_init() }
func file_loan_proto_init() {
	if File_loan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_proto_rawDesc), len(file_loan_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_proto_goTypes,
		DependencyIndexes: file_loan_proto_depIdxs,
		EnumInfos:         file_loan_proto_enumTypes,
		MessageInfos:      file_loan_proto_msgTypes,
	}.Build()
	File_loan_proto = out.File
	file_loan_proto_goTypes = nil
	file_loan_proto_depIdxs = nil
}
