// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: loan.proto

package loan

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_CreateLoan_FullMethodName       = "/loan.LoanService/CreateLoan"
	LoanService_ClaimLoan_FullMethodName        = "/loan.LoanService/ClaimLoan"
	LoanService_UpdateLoan_FullMethodName       = "/loan.LoanService/UpdateLoan"
	LoanService_GetLoanByID_FullMethodName      = "/loan.LoanService/GetLoanByID"
	LoanService_ListLoansByOwner_FullMethodName = "/loan.LoanService/ListLoansByOwner"
	LoanService_BanUser_FullMethodName          = "/loan.LoanService/BanUser"
	LoanService_DeliveryLoan_FullMethodName     = "/loan.LoanService/DeliveryLoan"
	LoanService_ConfirmDelivery_FullMethodName  = "/loan.LoanService/ConfirmDelivery"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*CreateLoanResponse, error)
	ClaimLoan(ctx context.Context, in *ClaimLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetLoanByID(ctx context.Context, in *GetLoanByIDRequest, opts ...grpc.CallOption) (*GetLoanByIDResponse, error)
	ListLoansByOwner(ctx context.Context, in *ListLoansByOwnerRequest, opts ...grpc.CallOption) (*ListLoansByOwnerResponse, error)
	BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeliveryLoan(ctx context.Context, in *DeliveryLoanRequest, opts ...grpc.CallOption) (*DeliveryLoanResponse, error)
	ConfirmDelivery(ctx context.Context, in *ConfirmDeliveryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) CreateLoan(ctx context.Context, in *CreateLoanRequest, opts ...grpc.CallOption) (*CreateLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_CreateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ClaimLoan(ctx context.Context, in *ClaimLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoanService_ClaimLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) UpdateLoan(ctx context.Context, in *UpdateLoanRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoanService_UpdateLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanByID(ctx context.Context, in *GetLoanByIDRequest, opts ...grpc.CallOption) (*GetLoanByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoanByIDResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoanByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ListLoansByOwner(ctx context.Context, in *ListLoansByOwnerRequest, opts ...grpc.CallOption) (*ListLoansByOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoansByOwnerResponse)
	err := c.cc.Invoke(ctx, LoanService_ListLoansByOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) BanUser(ctx context.Context, in *BanUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoanService_BanUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) DeliveryLoan(ctx context.Context, in *DeliveryLoanRequest, opts ...grpc.CallOption) (*DeliveryLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_DeliveryLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) ConfirmDelivery(ctx context.Context, in *ConfirmDeliveryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LoanService_ConfirmDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
type LoanServiceServer interface {
	CreateLoan(context.Context, *CreateLoanRequest) (*CreateLoanResponse, error)
	ClaimLoan(context.Context, *ClaimLoanRequest) (*emptypb.Empty, error)
	UpdateLoan(context.Context, *UpdateLoanRequest) (*emptypb.Empty, error)
	GetLoanByID(context.Context, *GetLoanByIDRequest) (*GetLoanByIDResponse, error)
	ListLoansByOwner(context.Context, *ListLoansByOwnerRequest) (*ListLoansByOwnerResponse, error)
	BanUser(context.Context, *BanUserRequest) (*emptypb.Empty, error)
	DeliveryLoan(context.Context, *DeliveryLoanRequest) (*DeliveryLoanResponse, error)
	ConfirmDelivery(context.Context, *ConfirmDeliveryRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) CreateLoan(context.Context, *CreateLoanRequest) (*CreateLoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLoan not implemented")
}
func (UnimplementedLoanServiceServer) ClaimLoan(context.Context, *ClaimLoanRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimLoan not implemented")
}
func (UnimplementedLoanServiceServer) UpdateLoan(context.Context, *UpdateLoanRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLoan not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanByID(context.Context, *GetLoanByIDRequest) (*GetLoanByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanByID not implemented")
}
func (UnimplementedLoanServiceServer) ListLoansByOwner(context.Context, *ListLoansByOwnerRequest) (*ListLoansByOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLoansByOwner not implemented")
}
func (UnimplementedLoanServiceServer) BanUser(context.Context, *BanUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method BanUser not implemented")
}
func (UnimplementedLoanServiceServer) DeliveryLoan(context.Context, *DeliveryLoanRequest) (*DeliveryLoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliveryLoan not implemented")
}
func (UnimplementedLoanServiceServer) ConfirmDelivery(context.Context, *ConfirmDeliveryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmDelivery not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_CreateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).CreateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_CreateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).CreateLoan(ctx, req.(*CreateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ClaimLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ClaimLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ClaimLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ClaimLoan(ctx, req.(*ClaimLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_UpdateLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).UpdateLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_UpdateLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).UpdateLoan(ctx, req.(*UpdateLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanByID(ctx, req.(*GetLoanByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ListLoansByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoansByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ListLoansByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ListLoansByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ListLoansByOwner(ctx, req.(*ListLoansByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_BanUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).BanUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_BanUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).BanUser(ctx, req.(*BanUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_DeliveryLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).DeliveryLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_DeliveryLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).DeliveryLoan(ctx, req.(*DeliveryLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_ConfirmDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).ConfirmDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_ConfirmDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).ConfirmDelivery(ctx, req.(*ConfirmDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoan",
			Handler:    _LoanService_CreateLoan_Handler,
		},
		{
			MethodName: "ClaimLoan",
			Handler:    _LoanService_ClaimLoan_Handler,
		},
		{
			MethodName: "UpdateLoan",
			Handler:    _LoanService_UpdateLoan_Handler,
		},
		{
			MethodName: "GetLoanByID",
			Handler:    _LoanService_GetLoanByID_Handler,
		},
		{
			MethodName: "ListLoansByOwner",
			Handler:    _LoanService_ListLoansByOwner_Handler,
		},
		{
			MethodName: "BanUser",
			Handler:    _LoanService_BanUser_Handler,
		},
		{
			MethodName: "DeliveryLoan",
			Handler:    _LoanService_DeliveryLoan_Handler,
		},
		{
			MethodName: "ConfirmDelivery",
			Handler:    _LoanService_ConfirmDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan.proto",
}
