// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users/ban": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Bans a user by their UUID, preventing them from creating new loans or borrowing books. This action is strictly restricted to Administrators.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin",
                    "loans"
                ],
                "summary": "Ban a user from the platform",
                "parameters": [
                    {
                        "description": "Ban User Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_loan_handler.BanUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user banned successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "invalid ban user request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "forbidden - admin access required",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "This method outputs the current status and metrics of the API Gateway",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Server Health Check",
                "responses": {
                    "200": {
                        "description": "everything is fine",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/loans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new loan record by calling the internal loan microservice. Only the user themselves can initiate the loan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Create a new loan",
                "parameters": [
                    {
                        "description": "Create Loan Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_loan_handler.CreateLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "loan successfully created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contracts.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data_message": {
                                            "$ref": "#/definitions/internal_handler_http_loan_handler.CreateLoanResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid create loan request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "you can not create loan",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a loan. Only the Lender (UserID) or Borrower (OwnerID) can update it. Note: The borrower cannot extend the deadline.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Update an existing loan",
                "parameters": [
                    {
                        "description": "Update Loan Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_loan_handler.UpdateLoanRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "loan updated successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "invalid update loan request",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "you can not update this loan / borrower cannot extend the deadline",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "404": {
                        "description": "loan record not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/loans/owner/{ownerID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all loans shared or owned by a specific user. Users can only fetch their own loan lists (ownerID must match the authenticated user ID).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "List loans by owner ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Owner User UUID",
                        "name": "ownerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "loans fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contracts.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data_message": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_handler_http_loan_handler.Loan"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid url param",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "you cannot access these loans",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/loans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the details of a specific loan using its UUID from the URL parameter. Only the Lender (UserID) or Borrower (OwnerID) involved in the loan can access it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Get loan details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "loan fetched successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contracts.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data_message": {
                                            "$ref": "#/definitions/internal_handler_http_loan_handler.GetLoanByIDResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid url param",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "you can not get loan",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "404": {
                        "description": "loan record not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/loans/{id}/claim": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows an authenticated user to claim/borrow an available book loan by its ID. The user cannot be the owner of the loan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Claim an available loan position",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user banned successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "invalid url param",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "forbidden - cannot claim own loan or user is banned",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "404": {
                        "description": "loan record not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "409": {
                        "description": "conflict - loan already claimed by another user",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/loans/{id}/confirm-delivery": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows the loan owner to input the 6-digit verification code received from the borrower to finalize and complete the loan.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Confirm loan delivery using OTP code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Delivery Code Body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_loan_handler.ConfirmDeliveryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "loan delivery confirmed successfully",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "invalid loan id or missing code",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "404": {
                        "description": "loan not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/loans/{id}/delivery": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of a loan to indicate that the book has been physically delivered. Returns a unique delivery confirmation code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "loans"
                ],
                "summary": "Mark a loan as delivered",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Loan UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "loan delivered successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/contracts.ResponseSuccess"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data_message": {
                                            "$ref": "#/definitions/internal_handler_http_loan_handler.DeliveryLoanResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "invalid url param",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "403": {
                        "description": "forbidden - you do not have permission to update this loan",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "404": {
                        "description": "loan not found",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "$ref": "#/definitions/contracts.ResponseError"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Accepts user credentials, validates them against the user service via gRPC, and returns a JWT access token upon successful authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Authenticate and login user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_user_handler.LoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"message\": \"user\t\t\t\t\t\t\t\t\t\t\t\t\t\tsuccessfully\tlogged\tin\", \"data\": { \"user_id\": \"string\", \"token\": \"string\", \"token_type\": \"string\" } }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{ \"code\": \"BAD_REQUEST\", \"message\": \"string\", \"details\": \"invalid\t\tuser\t\t\tlogin\trequest\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "{ \"code\": \"UNAUTHENTICATED\", \"message\": \"string\", \"details\": \"invalid\tusername\t\tor\t\tpassword\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{ \"code\": \"INTERNAL_SERVER_ERROR\", \"message\": \"string\", \"details\": \"\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "Accepts user registration details and registers a new account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_user_handler.RegisterUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{ \"message\": \"user\tsuccessfully\tregistered\", \"data\": { \"user_id\": \"string\", \"email\": \"string\", \"created_at\": \"string\" } }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{ \"code\": \"BAD_REQUEST\", \"message\": \"string\", \"details\": \"string\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{ \"code\": \"INTERNAL_SERVER_ERROR\", \"message\": \"string\", \"details\": \"\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/update": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing user's information via gRPC user service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user details",
                "parameters": [
                    {
                        "description": "User update details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler_http_user_handler.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"message\": \"user\t\t\t\t\t\t\t\t\t\t\t\t\tsuccessfully\tupdated\", \"data\": { \"user_id\": \"string\", \"name\": \"string\", \"email\": \"string\", \"username\": \"string\" } }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{ \"code\": \"BAD_REQUEST\", \"message\": \"string\", \"details\": \"invalid\tuser\t\t\tupdate\trequest\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{ \"code\": \"INTERNAL_SERVER_ERROR\", \"message\": \"string\", \"details\": \"\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches user details from the user microservice using their unique ID provided in the URL path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"message\": \"user\t\t\t\t\t\t\t\t\t\t\t\t\tsuccessfully\tfetched\", \"data\": { \"user_id\": \"string\", \"name\": \"string\", \"email\": \"string\", \"username\": \"string\" } }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{ \"code\": \"BAD_REQUEST\", \"message\": \"string\", \"details\": \"invalid\tget\t\t\t\tuser\trequest\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{ \"code\": \"INTERNAL_SERVER_ERROR\", \"message\": \"string\", \"details\": \"\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user account from the system using their unique ID provided in the URL path. Only the authenticated user themselves can delete their own account.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{ \"message\": \"user\t\t\t\t\t\t\t\t\t\t\t\t\tsuccessfully\tdeleted\", \"data\": null }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{ \"code\": \"BAD_REQUEST\", \"message\": \"string\", \"details\": \"invalid\tdelete\t\t\tuser\trequest\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "{ \"code\": \"FORBIDDEN\", \"message\": \"string\", \"details\": \"you\t\tdo\t\t\t\tnot\t\thave\tpermission\tto\tdelete\tthis\tuser\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{ \"code\": \"INTERNAL_SERVER_ERROR\", \"message\": \"string\", \"details\": \"\" }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "contracts.ResponseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "contracts.ResponseSuccess": {
            "type": "object",
            "properties": {
                "data_message": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_loan_handler.BanUserRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "expired_at": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_loan_handler.ConfirmDeliveryRequest": {
            "type": "object",
            "required": [
                "delivery_code"
            ],
            "properties": {
                "delivery_code": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_loan_handler.CreateLoanRequest": {
            "type": "object",
            "required": [
                "book_name",
                "owner_id"
            ],
            "properties": {
                "book_name": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_loan_handler.CreateLoanResponse": {
            "type": "object",
            "required": [
                "book_name",
                "id",
                "user_id"
            ],
            "properties": {
                "book_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_loan_handler.DeliveryLoanResponse": {
            "type": "object",
            "properties": {
                "delivery_code": {
                    "type": "string",
                    "example": "DEL-98765"
                }
            }
        },
        "internal_handler_http_loan_handler.GetLoanByIDResponse": {
            "type": "object",
            "required": [
                "loan"
            ],
            "properties": {
                "loan": {
                    "$ref": "#/definitions/internal_handler_http_loan_handler.Loan"
                }
            }
        },
        "internal_handler_http_loan_handler.Loan": {
            "type": "object",
            "required": [
                "book_name",
                "id",
                "user_id"
            ],
            "properties": {
                "book_name": {
                    "type": "string",
                    "example": "The Go Programming Language"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-06-03T12:00:00Z"
                },
                "deadline": {
                    "type": "string",
                    "example": "2026-06-16T18:30:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "loan-uuid-111"
                },
                "owner_id": {
                    "type": "string",
                    "example": "owner-uuid-456"
                },
                "status": {
                    "type": "string",
                    "example": "BORROWED"
                },
                "user_id": {
                    "type": "string",
                    "example": "user-uuid-123"
                }
            }
        },
        "internal_handler_http_loan_handler.UpdateLoanRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "book_name": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_user_handler.LoginUserRequest": {
            "type": "object",
            "required": [
                "credential",
                "password"
            ],
            "properties": {
                "credential": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_handler_http_user_handler.RegisterUserRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3
                }
            }
        },
        "internal_handler_http_user_handler.UpdateUserRequest": {
            "type": "object",
            "required": [
                "user_id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "تایپ کنید: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Books & Trust API Gateway",
	Description:      "این سرویس به عنوان درگاه اصلی برای دسترسی به میکروسرویس\u200cهای امانت و کاربران عمل می\u200cکند.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
