CREATE TABLE IF NOT EXISTS loans (
    id UUID PRIMARY KEY,
    owner_id UUID NOT NULL,
    book_name VARCHAR(255) NOT NULL,
    deadline TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);