ALTER TABLE loans ADD COLUMN IF NOT EXISTS status VARCHAR(255) NOT NULL DEFAULT 'unspecified';

ALTER TABLE loans ADD COLUMN IF NOT EXISTS returned_at TIMESTAMPTZ;

ALTER TABLE loans ADD COLUMN IF NOT EXISTS user_id UUID;

